### ISSUE TITLE
question 5.3.2

### ISSUE THREAD

**Issue by Ducasse** [pharo-mooc/PharoMooc#30]
gehef04/25/2020
@Stepharo I think question 5.3.2 - Check correct expressions in which file.txt contains the text Hello and the stream variable contains a file stream. - is not very good one :slight_smile: 
Stream>>#nextPut: clearly states it returns the given anObject (the argument). 
In its subclass WriteStream, WriteStream>>#nextPut: returns anObject (the argument). 
In its subclass StandardFileStream, StandardFileStream>>#nextPut: returns char (the argument). 
In its subclass MultiByteFileStream, MultiByteFileStream>>#nextPut: can return both argument and stream (which should be considered bug or at leasy very bad design) and furthermore, in given usage in the question it really returns the stream, although the method, according to how the API is defined in superclasses, should return the argument. I think returning stream is a bug and the question requires you to know that bug is there (which I did not although I know stream API pretty well, so I failed the question).
Whole MultiByteFileStream has been deprecated in P7, so there is no reason to report the bug itself, I just don't think people should be asked about it.

I've just stambled on this one too... two years later :wink:

**Comment by LucFabresse** [comment]
thanks!
we modified the quiz and it will be available in the next version of the MOOC.
